### ISSUE TITLE
Zenodo is not recognizing a new release of my github repository

### ISSUE THREAD

**Issue by alfkoehn** [zenodo/zenodo#2181]
Browser & OS (see also https://www.whatismybrowser.com/): Firefox 89: Ubuntu Linux

## Describe the bug
I have a repository with 1 release which is linked to zenodo and a doi. I have done this in April 2020 and now wanted to create a new release. According to the tutorial [1], zenodo should automatically detect if I make a new release (the webhook was already present), but this did not happened, i.e. zenodo has not reacted to the new release on github.
[1] https://guides.github.com/activities/citable-code/

## Steps to Reproduce
1. Login to github
2. Login to zenodo with my github account
3. Go to my github repository for which I want to create a new release
4. Check the settings to see if a webhook is present (it was from the previous initial release in April 2020)
5. Go to the Releases menu on github and create a new release (ending with finally clicking the Publish release button)
6. Go to zenodo to see that it has no recognized that a new release was created 

## Expected behavior
Zenodo should recognized that the package on github has a new release and should update it.

## Screenshots (if applicable)
not necessary (will provide, of course, if you consider it as helpful)

**Comment by boopsboops** [comment]
Same for me, pushed yesterday. The release is stuck on "Received" in yellow.

**Comment by alfkoehn** [comment]
Indeed, if I just click on "Upload" at the top navigation bar on zenodo, the release does not appear there. But when I click on the dropdown menu in the top right corner (at the zenodo webpage) and choose "GitHub" and then click on the repository in the "Enabled repositories" menu, the new release does appear there with a yellow "Received" label (as shown in the screenshot).

![zenodo_github_release_stuck](https://user-images.githubusercontent.com/23075232/121401885-8bd20000-c959-11eb-9d19-082dc33e4f4c.png)

**Comment by leabeaumelle** [comment]
Same issue for me. Repo is stuck in yellow "received". I manually uploaded my release but even then, no connexion between the doi in the "upload" section and the "github enabled repository". How to solve this?

**Comment by albertvillanova** [comment]
Same problem here. My release was done on 2021-06-08 and it appears in yellow as "Received" (instead of in green as Published).

Maybe there was a problem for the releases done that day? 2021-06-08.

**Comment by arcangelo7** [comment]
The problem should have been solved. Try to check if it works now.

**Comment by albertvillanova** [comment]
Yes, it is fixed. Thanks.
Regards,
Albert.

**Comment by alfkoehn** [comment]
Works for me, problem is fixed, thanks!

**Comment by boopsboops** [comment]
My release is not fixed yet. Still stuck on "Received". The project DOI [10.5281/zenodo.4443447](https://doi.org/10.5281/zenodo.4443447) should resolve to v243 as released on GitHub as [v243](https://github.com/genner-lab/meta-fish-lib/releases/tag/v243), but is still stuck on v242. Cheers.

**Comment by alfkoehn** [comment]
> My release is not fixed yet. Still stuck on "Received". The project DOI [10.5281/zenodo.4443447](https://doi.org/10.5281/zenodo.4443447) should resolve to v243 as released on GitHub as [v243](https://github.com/genner-lab/meta-fish-lib/releases/tag/v243), but is still stuck on v242. Cheers.

That's weird, i would suggest to contact the zenodo support team, they usually reply within a few hours.
