### ISSUE TITLE
utf8 broken preview for markdown

### ISSUE THREAD

**Issue by fungs** [zenodo/zenodo#935]
It seems that the markdown renderer in the preview window does not display UTF8 encoded markdown files correctly although this is the standard text encoding on most systems nowadays.

Example:
https://zenodo.org/record/201076

**Comment by lnielsen** [comment]
Thanks. We'll take a look.

**Comment by krzysztof** [comment]
MD previewing code: https://github.com/inveniosoftware/invenio-previewer/blob/master/invenio_previewer/extensions/mistune.py

**Comment by jainaman224** [comment]
I would like to work on this issue.

**Comment by jainaman224** [comment]
ö decodes to \xc3\xb6 and then rendered as \xc3 and \xb6 separately.

**Comment by jainaman224** [comment]
Error found: safe is causing this issue at https://github.com/inveniosoftware/invenio-previewer/blob/master/invenio_previewer/templates/invenio_previewer/mistune.html#L32.

**Comment by DeadlyHollows** [comment]
Is this issue is still open?

**Comment by fungs** [comment]
@DeadlyHollows the entry I reported still looks the same, so I guess it is.

**Comment by jainaman224** [comment]
@DeadlyHollows This issue is related to `invenio-previewer` and closed but suggestions are welcomed.
@fungs This still looks same because till the next release we are not updating the api dependencies.

**Comment by lnielsen** [comment]
Closing as it was fixed in Invenio-Previewer

**Comment by syrte** [comment]
Confusing. Maybe I am wrong, but this issue does not seem resolved.
I found the rendering of https://zenodo.org/records/201076 still does not look right.
I got a similar problem with my files.
